### ISSUE TITLE
Optimise content storage

### ISSUE THREAD

**Issue by alexmshepherd** [owdex/owdex#36]
The content of a webpage is directly read and stored. This includes words like "and", "the" etc ("stop words"). It also may include a lot of redundant whitespace, and "structural" components like "Skip to content". Storage space could be optimised by ignoring these parts of the content. 

It's worth noting that the description, if it's not present in the meta-description tag, would need to be set from the content _before_ the stop words are taken out, otherwise descriptions will look a bit unusual.

---

**Edit:** The scope of this issue should only apply to whitespace and structural components.

**Comment by 4censord** [comment]
Cleaning up whitespace sounds reasonable.
But, removing stop words might mess with the lucene search algorithm, as its is optimized for natural language

**Comment by alexmshepherd** [comment]
Good point. Another consideration would be that it would make it impossible to search "within quotes" to find a particular phrase.
