### ISSUE TITLE
Fix build action

### ISSUE THREAD

**Issue by alexmshepherd** [owdex/owdex#52]
We want to build on PR, but only push an image on merge or release.

https://stackoverflow.com/questions/75958037/build-on-pr-but-only-push-image-on-merge-or-release

I genuinely have no idea how to solve this.

**Comment by 4censord** [comment]
I may take a look at this.

For clarification:

An image should be pushed to the registry on:
* tags (releases)
* merges (new commits on master)

An image should be build, but not pushed on:
* pull requests?


AFAIK it is at least common to build and push on pull requests (with tags like pr-123), so the new image can be tested without hassle.

It there a reason why we don't want that?

**Comment by alexmshepherd** [comment]
I guess we can. It would probably simplify things a lot. I'll just re-enable that and then I can stop thinking about GH Actions bullshit ;)
